// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSentinel returns the embedded CollectionSpec for sentinel.
func loadSentinel() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SentinelBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sentinel: %w", err)
	}

	return spec, err
}

// loadSentinelObjects loads sentinel and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sentinelObjects
//	*sentinelPrograms
//	*sentinelMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSentinelObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSentinel()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sentinelSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sentinelSpecs struct {
	sentinelProgramSpecs
	sentinelMapSpecs
	sentinelVariableSpecs
}

// sentinelProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sentinelProgramSpecs struct {
	SentinelPulse *ebpf.ProgramSpec `ebpf:"sentinel_pulse"`
}

// sentinelMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sentinelMapSpecs struct {
	GlobalStats *ebpf.MapSpec `ebpf:"global_stats"`
}

// sentinelVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sentinelVariableSpecs struct {
}

// sentinelObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type sentinelObjects struct {
	sentinelPrograms
	sentinelMaps
	sentinelVariables
}

func (o *sentinelObjects) Close() error {
	return _SentinelClose(
		&o.sentinelPrograms,
		&o.sentinelMaps,
	)
}

// sentinelMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type sentinelMaps struct {
	GlobalStats *ebpf.Map `ebpf:"global_stats"`
}

func (m *sentinelMaps) Close() error {
	return _SentinelClose(
		m.GlobalStats,
	)
}

// sentinelVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type sentinelVariables struct {
}

// sentinelPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSentinelObjects or ebpf.CollectionSpec.LoadAndAssign.
type sentinelPrograms struct {
	SentinelPulse *ebpf.Program `ebpf:"sentinel_pulse"`
}

func (p *sentinelPrograms) Close() error {
	return _SentinelClose(
		p.SentinelPulse,
	)
}

func _SentinelClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sentinel_bpfel.o
var _SentinelBytes []byte
